package:
  name: ros-noetic-rosserial-python
  version: 0.9.2
source:
  git_url: https://github.com/ros-gbp/rosserial-release.git
  git_rev: release/noetic/rosserial_python/0.9.2-1
  folder: ros-noetic-rosserial-python/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 9
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - setuptools
    - sel(unix): make
    - sel(unix): coreutils
    - sel(osx): tapi
    - sel(build_platform != target_platform): pkg-config
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): numpy
  host:
    - numpy
    - pip
    - sel(build_platform == target_platform): pkg-config
    - pyserial
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-catkin
    - ros-noetic-diagnostic-msgs
    - ros-noetic-rospy
    - ros-noetic-rosserial-msgs
  run:
    - pyserial
    - python
    - ros-distro-mutex 0.4 noetic
    - ros-noetic-diagnostic-msgs
    - ros-noetic-rospy
    - ros-noetic-rosserial-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
